### PR TITLE
replaced / with the proper file separator

### PR DESCRIPTION
**Pull request by jchenry**
@tjmilligan can you please approve this and endorse my addition as maintainer of the project?

### CODE REVIEW

**Comment by tjmilligan** [comment]
What is the mechanism to
          endorse you as maintainer of the project?  I am unable log
          onto my Jenkins infrastructure account, which was associated
          with my Skytap email, which likely no longer exists.
    
    
        
        Tom Milligan
        
        tomm@milligannet.org
        
      
    On 10/9/17 4:43 PM, Colin Henry wrote:
    
    
      @tjmilligan can you please approve
        this and endorse my addition as maintainer of the project?
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2
      Commit Summary
      
        replaced / with the proper file separator
      
      File Changes
      
         M src/main/java/org/jenkinsci/plugins/skytap/SkytapUtils.java
          (3) 
      
      Patch Links:
      
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2.patch
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2.diff
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jenkinsci/skytap-cloud-plugin","title":"jenkinsci/skytap-cloud-plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jenkinsci/skytap-cloud-plugin"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"replaced / with the proper file separator (#2)"}],"action":{"name":"View Pull Request","url":"https://github.com/jenkinsci/skytap-cloud-plugin/pull/2"}}}

**Comment by jchenry** [comment]
@tjmilligan there is a thread on the developer's list I started outlining the situation(https://groups.google.com/forum/#!searchin/jenkinsci-dev/skytap%7Csort:relevance/jenkinsci-dev/SygEDSaQFyY/vp6FosncBgAJ), and if you could comment on that, I would really appreciate it. Please mention this PR in the thread as well. 

Thanks!

**Comment by tjmilligan** [comment]
Change has been merged.  I
          have responded to the jenkinsci Google group thread.
    
    
        
        Tom Milligan
        
        tomm@milligannet.org
        
      
    On 10/9/17 4:43 PM, Colin Henry wrote:
    
    
      @tjmilligan can you please approve
        this and endorse my addition as maintainer of the project?
      
      You can view, comment on, or merge this pull request online
        at:
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2
      Commit Summary
      
        replaced / with the proper file separator
      
      File Changes
      
         M src/main/java/org/jenkinsci/plugins/skytap/SkytapUtils.java
          (3) 
      
      Patch Links:
      
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2.patch
        https://github.com/jenkinsci/skytap-cloud-plugin/pull/2.diff
      
      —
        You are receiving this because you were mentioned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      
        
          
          
        
        
      
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/jenkinsci/skytap-cloud-plugin","title":"jenkinsci/skytap-cloud-plugin","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/jenkinsci/skytap-cloud-plugin"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"replaced / with the proper file separator (#2)"}],"action":{"name":"View Pull Request","url":"https://github.com/jenkinsci/skytap-cloud-plugin/pull/2"}}}

**Comment by tjmilligan** [comment]
Yes, please make Colin Henry the new maintainer of the Skytap Plugin

TM

**Pull request merged**
